# Default config file for labyrinth

# General parameters
# Set the random seed for reproducibility
random_seed: 0

prompt:
  # The first prompt that we will give to the model
  prompt_dir: "virgil/labyrinth/config"
  initial_prompt: "prompt.txt"
  per_room_prompt: "per_room_prompt.txt"
  image_prompt: "image_prompt.txt"

# Maze parameters - configures how big the maze is and whether to visualize it
maze:
  height: 2
  width: 2
  visualize: False

# LLM setup - configures the LLM to use and its parameters
# backend: "gemma-2b-it"
backend: "qwen-1.5B"

chat:
  max_history_length: 100  # Maximum number of messages to keep in chat history
  messages_to_preserve: 2  # Keep the first 2 messages in chat history


world1:
  # The world that the player will explore
  goal: "a treasure chest containing an ancient relic that grants eternal youth"
  location: "a crumbling, ruined castle filled with traps and monsters"
  writing_style: "poetic, evocative, and mysterious; inspired by Edgar Allan Poe."
  image_style: "baroque oil painting; beautiful, sinister, and mysterious. high-quality painting."

world: 
  goal: "an AI server containing the secrets of the universe"
  location: "a futuristic, high-tech research facility"
  writing_style: "poetic, dream-like, and philosophical. inspired by Philip K. Dick."
  image_style: "50's sci-fi art; retro-futuristic, colorful, and imaginative. high-quality sci-fi art."

world3:
  goal: "a witch's cabin deep in the forest"
  location: "a dark, misty forest filled with strange creatures and ancient magic"
  writing_style: "eerie, strange, fairy-tale-like; inspired by the works of Neil Gaiman"
  image_style: "dark fantasy art; eerie, mysterious, and magical. high-quality fantasy art."
