# Default config file for labyrinth

# General parameters
# Set the random seed for reproducibility
random_seed: 0

prompt:
  # The first prompt that we will give to the model
  prompt_dir: "virgil/labyrinth/config"
  initial_prompt: "prompt.txt"
  per_room_prompt: "per_room_prompt.txt"

# Maze parameters - configures how big the maze is and whether to visualize it
maze:
  height: 5
  width: 5
  visualize: True

# LLM setup - configures the LLM to use and its parameters
# backend: "gemma-2b-it"
backend: "qwen-1.5B"

chat:
  max_history_length: 100  # Maximum number of messages to keep in chat history
  messages_to_preserve: 2  # Keep the first 2 messages in chat history

