# Default config file for labyrinth

# General parameters
# Set the random seed for reproducibility
random_seed: 0

prompt:
  # The first prompt that we will give to the model
  prompt_dir: "virgil/labyrinth/config"
  initial_prompt: "prompt.txt"
  per_room_prompt: "per_room_prompt.txt"
  image_prompt: "image_prompt.txt"

# Maze parameters - configures how big the maze is and whether to visualize it
maze:
  height: 2
  width: 2
  visualize: False

# LLM setup - configures the LLM to use and its parameters
# backend: "gemma-2b-it"
backend: "qwen-1.5B"

chat:
  max_history_length: 100  # Maximum number of messages to keep in chat history
  messages_to_preserve: 2  # Keep the first 2 messages in chat history


world:
  goal: "a treasure chest containing an ancient relic that grants eternal youth"
  location: "a crumbling, ruined castle filled with traps and monsters"
  writing_style: "poetic, evocative, and mysterious; inspired by the works of Edgar Allan Poe"
