import os
from virgil.audio.music import MusicGenerator


def generate_audiocraft_examples():
    output_dir = "audiocraft_examples"
    os.makedirs(output_dir, exist_ok=True)

    audiocraft_models = {
        "audiocraft-melody": "Generates melodic sequences.",
        "audiocraft-drums": "Generates drum patterns and rhythms.",
        "audiocraft-bass": "Generates basslines.",
        "audiocraft-guitar": "Generates guitar riffs and melodies.",
        "audiocraft-piano": "Generates piano compositions.",
        "audiocraft-speech": "Generates speech-like audio.",
    }

    for model_name, description in audiocraft_models.items():
        print(f"\n--- Model: {model_name} ---")
        print(f"Description: {description}")
        print(f"Generating example for model: {model_name}")
        generator = MusicGenerator(model=model_name)
        text_prompt = f"A short musical phrase generated by {model_name}."
        output_path = os.path.join(output_dir, f"{model_name.replace('-', '_')}.wav")
        generator.generate(text=text_prompt, output_path=output_path)
        print(f"Saved to {output_path}")


if __name__ == "__main__":
    generate_audiocraft_examples()
